services:
  riven:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: riven
    restart: unless-stopped
    tty: true
    shm_size: 1024m
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ORIGIN=http://localhost:8080
      - RIVEN_FORCE_ENV=true
      - RIVEN_DATABASE_HOST=${RIVEN_DATABASE_HOST}
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./container_data/riven:/riven/data
      - ./container_data/mount:/mount:rshared,z
    depends_on:
      riven_postgres:
        condition: service_healthy

  riven_postgres:
    image: postgres:17-alpine
    container_name: riven_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riven
    ports:
      - "5432:5432"
    volumes:
      - ./container_data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
