name: Verify

on:
  pull_request:
    branches:
      - main

jobs:
  backend-battery:
    name: Backend Battery
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true

      - name: Install pre-requisites
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse3-dev pkg-config

      - name: Install the project
        run: uv sync --group dev --frozen

      - name: Ruff & Isort
        run: |
          uv run ruff check ./src
          uv run isort --check-only ./src

      - name: Type check
        uses: jakebailey/pyright-action@v1
        with:
          pylance-version: latest-release

      - name: Run tests
        run: uv run pytest src
